sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3



## Cache composer
cache:
  directories:
  - $HOME/.composer/cache

env:
  matrix:
    - AUTOLOAD=1
    - AUTOLOAD=0

before_install:
  # Install various build dependencies. We use `travis_retry` because Composer
  # will occasionally fail intermittently.
  - travis_retry composer install

before_script:
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script: ./build.php ${AUTOLOAD}

after_script: ./vendor/bin/coveralls -v